### ISSUE TITLE
IPv6 Todo List

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#883]
Please feel free to pickup any of these if you feel you have the knowledge and skills to assist.

**TODO:**
- [ ]  **General: investigate why WAN6 does not always come up on its own. Sometimes needs a kickstart (ifup wan6), sometimes doesn't. May be a missing call somewhere.**
- [ ] General: cleanup tab vs space indentation. Got my editors mixed up and i've caused quite a mess. Any suggestions for cleaning this up without ruining git history much appreciated.
- [ ] General: cleanup duplicated code (some things could be done better and more efficiently)
-[ ]  General: cleanup use of _full format_ ipv6 addresses. We should prefer canonical where possible. This also means that we compare apples to apples and don't end up considering `2001:db8::` differently to `2001:db8:0000::` etc.
- [ ] Connection -> Basic: PPPoE untested. Need guinea pigs who are advanced users.
- [ ] **Firewall: More generally support the _negative netmask_ notation for IPv6 to handle dynamic global prefixes from ISPs.**
  - [ ] QoS should already support this
  - [ ] bandwidth/quotas need slight modifications to their subnet comparison modules to support this. No plan of attack yet.
  - [ ] Webmon/Weburl probably need similar modifications
  - [ ] Restrictions should be fine out of the box, except for the bits which rely on quotas.
  - [ ] Need to accept the negative subnet notation throughout the GUI (where appropriate)
- [ ] gargoyle_header_footer: `current_lan_ip6` and `current_wan_ip6` need to be fixed so they can fetch from UCI as well as just the interface. Tricky part is that these interfaces can have > 1 IP listed in UCI, so we need to bring them in as a list rather than static options. No big deal, just haven't done it yet.
- [ ] qosmon: ping target IPv6 capability not done. 
- [ ] plugin-gargoyle-openvpn: Not done (low priority, not sure of the benefits here). At a minimum need to ensure the block non ovpn traffic rules works over ipv6 as well.
- [ ] plugin-gargoyle-wireguard: Not done (low priority, not sure of the benefits here). At a minimum need to ensure the block non wg traffic rules works over ipv6 as well.
- [ ] plugin-gargoyle-ddns: Not yet done (relies on ewget)
- [ ] plugin-gargoyle-tor: Not done (low priority, not sure of the benefits here)
- [ ] plugin-gargoyle-usb_storage: Have not checked any of the file sharing over IPv6. In theory should be automatic.
- [ ] plugin-gargoyle-webcam: Not done (don't have any webcam so can't test)
- [ ] plugin-gargoyle-usb_printer: Not done (don't have any printer so can't test)
- [ ] plugin-gargoyle-minidlna: Not yet done
- [ ] plugin-gargoyle-ping-watchdog: Not yet done
- [ ] plugin-gargoyle-pptp: Not done (low priority)
- [ ] plugin-gargoyle-adblock: Not done (low priority)

**Comment by livepu** [comment]
Fortunately, I am looking forward to perfection

**Comment by lantis1008** [comment]
plugin-gargoyle-usb_storage:
CIFS supports IPV6 out of the box. I couldn't make it work on Windows 10, but an Ubuntu client connected no problem.
FTP (vsftpd) supports IPV6, but you need to set `listen_ipv6=yes` and `listen=no` specifically to enable it. You cannot run a single instance for both, so we may need to look at starting two instances to support both at the same time.
NFS supports IPV6 out of the box.

**Comment by lantis1008** [comment]
plugin-gargoyle-minidlna:
minidlna only supports ipv4 currently. Significant work to maintain a local patch for IPv6. Won't do.
